runtime: nodejs18
metadata:
  name: SERVER
spec:
  template:
      run.googleapis.com/secrets: DB_PASSWORD:projects/364055912546/secrets/DB_PASSWORD
    spec:
      containers:
      - env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: DB_PASSWORD
