runtime: nodejs18
metadata:
  name: SERVER
spec:
  template:
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: DB_PASSWORD
