name: Server CI

on:
  push:
    branches: ["master"]
    paths:
      - "*/**"
      - "!client/**"
      - "!*/*-client.yml"

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "drawspace-api"
          heroku_email: "ruydelgado@gmail.com"
          appdir: "server"
          buildpack: "heroku/nodejs"
