name: Server CI

on:
  push:
    branches: ["master"]
    paths:
      - "packages/**"
      - "server/**"
      - ".github/workflows/deploy-server.yml"

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
