name: Client CI

on:
  push:
    branches: ['master']
    paths:
      - 'workspaces/lib/**'
      - 'workspaces/client/**'
      - '.github/workflows/deploy-client.yml'

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: package.json set ${{ github.repository }} path as homepage for gh-pages
        uses: jaywcjlove/github-action-package@main
        env:
          REPOPATH: ${{ github.repository#*/ }}
        with:
          data: |
            {
              "homepage": "${{ env.REPOPATH }}"
            }

      - name: Build
        run: |
          yarn install
          yarn workspace client build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./workspaces/client/build
