name: 'Deploy: Google Cloud'
on:
  push:
    branches: ['develop']
    paths:
      - 'workspaces/**'
      - '.github/workflows/**'
env:
  VM_NAME: 'drawserver'
  PROJECT: 'mstream-368503'
  PROJECT_NO: 364055912546
  ZONE: 'us-central1-a'

jobs:
  changes:
    runs-on: 'ubuntu-latest'
    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
      killswitch: ${{ steps.filter.outputs.killswitch }}
    steps:
      - uses: 'actions/checkout@v3'
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client:
              - 'workspaces/lib/**'
              - 'workspaces/client/**'
            server:
              - 'workspaces/lib/**'
              - 'workspaces/server/**'
              - '.github/workflows/deploy-google.yml'
            killswitch:
              - 'workspaces/function-gkill/**'

  tests:
    needs: [changes]
    runs-on: 'ubuntu-latest'
    if: ${{ needs.changes.outputs.client == 'true' || needs.changes.outputs.server == 'true' }}
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: yarn install --immutable

      - name: Server Tests
        if: ${{ needs.changes.outputs.server == 'true' }}
        run: yarn workspace server test

      - name: Client Tests
        if: ${{ needs.changes.outputs.client == 'true' }}
        run: yarn workspace client test

  function_killswitch_deploy:
    needs: [changes]
    if: ${{ needs.changes.outputs.killswitch == 'true' && github.ref == 'refs/heads/master' }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/364055912546/locations/global/workloadIdentityPools/default-pool/providers/github-provider'
          service_account: 'github@mstream-368503.iam.gserviceaccount.com'

      - name: 'install'
        run: yarn install --immutable

      - name: 'build'
        run: yarn workspace gkill build

      - name: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'function-killswitch'
          runtime: 'nodejs16'
          entry_point: 'main'
          source_dir: 'workspaces/function-gkill/dist'
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/mstream-368503/topics/budget

  client_bucket_deploy:
    needs: [changes, tests]
    if: ${{ false }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/364055912546/locations/global/workloadIdentityPools/default-pool/providers/github-provider'
          service_account: 'github@mstream-368503.iam.gserviceaccount.com'

      - name: 'install'
        run: yarn install --immutable

      - name: 'build'
        run: |
          yarn workspace client build

      - name: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'workspaces/client/build'
          destination: 'mtoon'
          parent: false

  server_deploy:
    needs: [changes, tests]
    if: ${{ needs.changes.outputs.server == 'true' }}
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/364055912546/locations/global/workloadIdentityPools/default-pool/providers/github-provider'
          service_account: 'github@mstream-368503.iam.gserviceaccount.com'

      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            DB_URL:364055912546/DB_URL

      - name: 'install'
        run: yarn install --immutable

      - name: 'build'
        run: |
          yarn workspace server build
          cp workspaces/server/app.yaml workspaces/server/dist/app.yaml

      - name: '.env'
        run: 'echo "DB_URL=$DB_URL" >> workspaces/server/dist/.env'
        shell: bash
        env:
          DB_URL: ${{ steps.secrets.outputs.DB_URL }}

      - name: 'tag'
        run: echo 'gcr.io/${{ env.PROJECT }}/${{ env.VM_NAME }}.${{ github.ref_name }}:latest' >> $GITHUB_OUTPUT

      - name: 'docker.push.artifactRegistry'
        run: |
          docker build -t $TAG workspaces/server/dist
          docker push $TAG
        env:
          TAG: ${{ steps.tag.outputs.output1 }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: 'vm.check'
        run: |
          # check if it exists 
          gcloud compute instances describe $VM_NAME > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "VM exists, continuing"
            echo 0 >> $GITHUB_OUTPUT
          else
            echo "VM does not exist"
            echo 1 >> $GITHUB_OUTPUT
            gcloud compute instances create-with-container $VM_NAME \
              --zone $ZONE \
              --container-image $TAG
          fi

      - name: 'vm.trigger.redeploy'
        run: |
          gcloud compute instances update-container $VM_NAME \
            --zone $ZONE \
            --container-image $TAG
