name: Client Delivery

on:
  push:
    branches: ["master"]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build -w client
          git config --global user.email "ruydelgado@gmail.com"
          git config --global user.name = "CI"
          git config --global user.password = "${{ secrets.GITHUB_TOKEN  }}$"
          npm run deploy -w client
