name: 'Deploy: Google Cloud'
on:
  push:
    paths:
      - 'workspaces/function-gkill/**'
      - '.github/workflows/deploy-google.yml'

jobs:
  changes:
    runs-on: 'ubuntu-latest'
    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
      killswitch: ${{ steps.filter.outputs.killswitch }}
    steps:
      - uses: 'actions/checkout@v3'
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client:
              - 'workspaces/client/**'
            server:
              - 'workspaces/server/**'
            killswitch:
              - 'workspaces/function-gkill/**'

  prepare:
    needs: [changes]
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/364055912546/locations/global/workloadIdentityPools/default-pool/providers/github-provider'
          service_account: 'github@mstream-368503.iam.gserviceaccount.com'
      - name: 'install'
        run: |
          yarn install

  function_killswitch_deploy:
    needs: [changes, prepare]
    if: ${{ needs.changes.outputs.killswitch == 'true' }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'build'
        run: yarn install && yarn workspace gkill build

      - name: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'function-killswitch'
          runtime: 'nodejs16'
          entry_point: 'main'
          source_dir: 'workspaces/function-gkill/dist'
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/mstream-368503/topics/budget

  client:
    needs: [changes, prepare]
    if: ${{ needs.changes.outputs.client == 'true' }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'build'
        run: yarn install && yarn workspace client build

      - name: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'workspace/client/build'
          destination: 'mtoon'
          parent: false
