name: Server CI

on:
  push:
    branches: ["master"]
    paths:
      - "*/**"
      - "!client/**"
      - "!*/*-client.yml"

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install and build
        run: |
          npm install -w server
          npm run build -w server

      - name: copy build output to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          FOLDER: server/build
          BRANCH: heroku
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
