name: 'Deploy: Client: Firebase Review App'
on:
  push:
    branches:
      - master
    paths:
      - 'workspaces/client/**'
      - '.github/workflows/firebase*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'install'
        run: yarn install --immutable

      - name: 'build'
        run: |
          yarn workspace client build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRAWSPACE_6C652 }}'
          channelId: live
          projectId: drawspace-6c652
          entryPoint: 'workspaces/client'
